### ISSUE TITLE
Sensor attributes 

### ISSUE THREAD

**Issue by Tom-ahawk** [custom-components/templatesensor#1]
The native template sensor lacks the functionality to add attributes. 

Please consider this functionality for this custom Template sensor. Sorry to say I don’t have the knowledge to contribute to the development. 

Cheers.

**Comment by ludeeus** [comment]
How should this be done?
What types of attributes are needed, and how advanced would the templates for those be?

Remember that it would have to be configured in the UI.

**Comment by Tom-ahawk** [comment]
My initial thought is that the attribute names  are defined in the GUI (+ for new attributes).  
Maybe also state the attribute type in the GUI(?)

Attribute values are defined similar as the state value, - getting values from other sensors state/attribute/template  or a constant. Or also from a variable if you use the, custom component Variables.

**Comment by ludeeus** [comment]
Both name and value needs to be defined.

**Comment by ludeeus** [comment]
Sorry this will not be implemented.
