### ISSUE TITLE
Add ability to customize update params 

### ISSUE THREAD

**Issue by gary-reyes** [custom-components/templatesensor#2]
I have converted all my sensor templates to use this component except a couple. In order to get these sensors to work I had to specify the template sensor to update on sensor.time updates since I am using {{now()}}. 

Questions :  
1. When does a sensor update? It seems like it may be evaluates at the default scan interval? 
2. Would it be possible to indicate a scan interval for evaluation or an entity to trigger on that may not be in the template?

**Comment by ludeeus** [comment]
1: It does.
2: Probably not. _I may add some more logic to it in the future._
