### ISSUE TITLE
Group created templates within integration panel 

### ISSUE THREAD

**Issue by johntdyer** [custom-components/templatesensor#3]
**Is your feature request related to a problem? Please describe.**
Today when I make two or more templates using the integration panel I end up with that many rows, one for each template which could get out of hand quickly.  Other integrations are grouped at the high level and then clicking into the type then shows the collection ( in this case templates ).

**Describe the solution you'd like**
I'd like it to show one row for template sensors with all the templates inside that panel 

**Additional context**

<img width="924" alt="image" src="https://user-images.githubusercontent.com/58234/63383385-a98c3a80-c36a-11e9-90ac-c486bcbe2078.png">

**Comment by ludeeus** [comment]
That is not possible, those lines are tied to the configuration, onle line pr configuration.
