### ISSUE TITLE
[Feature Request] Ability to change template

### ISSUE THREAD

**Issue by noxhirsch** [custom-components/templatesensor#4]
**Is your feature request related to a problem? Please describe.**
My smart home is always in change. So sometimes I need to change the config - in this case I need to update the template parameters of the sensor. At the moment this is not possible (at least not in the UI - maybe somewhere in the .storage folder)

**Describe the solution you'd like**
It would be great if you could change the template afterwards.

**Describe alternatives you've considered**
An alternative would be, that you can see the template somewhere to copy it and recreate that sensor (maybe this could be in a static second sensor)

**Additional context**

**Comment by ludeeus** [comment]
This is not possible to add.

You can find the template you are using in `.storage/core.config_entries`

**NB!: Do _not_ change that file!, _only_ copy things from it!**
